apiVersion: v1
clusters:
  - cluster:
      # todo: replace with your base64 encoded CA certificate
      certificate-authority-data: <base64_ca_certificate>
      # todo: replace with your MCP API server endpoint
      server: <api_shoot_endpoint>
    name: openmcp-canary
contexts:
  - context:
      cluster: openmcp-canary
      namespace: default
      user: openmcp-canary
    name: openmcp-canary
current-context: openmcp-canary
kind: Config
users:
  - name: openmcp-canary
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          # todo: replace with your OIDC issuer URL and client ID
          - --oidc-issuer-url=<issuer-url>
          - --oidc-client-id=<client-id>
          - --oidc-extra-scope=email
          - --oidc-extra-scope=profile
          - --oidc-extra-scope=offline_access
          - --oidc-use-pkce
          - --grant-type=auto
        command: kubectl
