---
apiVersion: v1
clusters:
  - cluster:
      # todo: replace with your base64 encoded CA certificate
      certificate-authority-data: <base64_ca_certificate>
      # todo: replace with your MCP API server endpoint
      server: <api_shoot_endpoint>
    name: mcp-project-poc-bmi-opendesk--ws-poc-bmi-opendesk-poc-bmi-opendesk
contexts:
  - context:
      cluster: mcp-project-poc-bmi-opendesk--ws-poc-bmi-opendesk-poc-bmi-opendesk
      namespace: default
      user: openmcp
    name: mcp-project-poc-bmi-opendesk--ws-poc-bmi-opendesk-poc-bmi-opendesk--openmcp
current-context: mcp-project-poc-bmi-opendesk--ws-poc-bmi-opendesk-poc-bmi-opendesk--openmcp
kind: Config
preferences: {}
users:
  - name: openmcp
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - oidc-login
          - get-token
          - --oidc-issuer-url=<issuer-url>
          - --oidc-client-id=<client-id>
          - --oidc-use-pkce
          - --grant-type=auto
          - --oidc-extra-scope=offline_access
          - --oidc-extra-scope=email
          - --oidc-extra-scope=profile
        command: kubectl
        env: null
        provideClusterInfo: false
