apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: sci-hcp03-tls-cert
  namespace: default
spec:
  commonName: "*.opendeskocm.shoot.example.com"
  secretRef:
    name: opendesk-certificates-tls
    namespace: default
