apiVersion: v1
kind: ServiceAccount
metadata:  
  name: openmcp-landscaper
  namespace: default  
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: sa-openmcp-landscaper-token
  annotations:
    kubernetes.io/service-account.name: openmcp-landscaper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:  
  name: sa-openmcp-landscaper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: openmcp-landscaper
  namespace: default
