apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: sci-hcp03-opendeskocm
  namespace: default
  annotations:
    landscaper.gardener.cloud/reconcile-if-changed: "true"

spec:
  context: sci-hcp03-opendeskocm

  componentDescriptor:
    ref:
      componentName: opendesk.poc.sap.com/base
      version: 0.1.2-6-gdfa6567
  blueprint:
    ref:
      resourceName: blueprint
  exports: {}
  # Set values for the import parameters of the blueprint
  imports:
    data:
      - name: release
        dataRef: sci-cluster-opendeskocm-release
      - name: base
        dataRef: sci-cluster-opendeskocm-base
      - name: environmentsDefaults
        dataRef: sci-cluster-opendeskocm-environments-defaults
      - name: theme
        dataRef: sci-cluster-opendeskocm-theme

    targets:
      - name: cluster # name of an import parameter of the blueprint
        target: sci-hcp03-opendeskocm # name of the Target custom resource containing the kubeconfig of the target cluster      
