# see https://github.com/gardener/landscaper/blob/master/docs/technical/target_types.md
apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Target
metadata:
  name: sci-hcp03-opendeskocm
  namespace: default
spec:
  type: landscaper.gardener.cloud/kubernetes-cluster
  secretRef:
    name: sci-hcp03-opendeskocm-service-account-kubeconfig
